name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: deniom3
  DOCKER_CONTAINER_NAME: smtp_to_telegram
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Prepare
        id: prepare
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "latest")
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          
      - run: echo "ST_VERSION=$(git describe --tags --always)" >> $GITHUB_OUTPUT
        id: git_version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
            ghcr.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
