name: test

on:
  pull_request: {}
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go build -v ./...
      - run: go test -v ./...
      - run: go vet ./...
      - run: test -z `go fmt`
